name: Test

on:
  push:
  workflow_dispatch:

jobs:
  harumph:
    name: Harumph things
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout Repository

      - name: pinging
        run: |
         curl http://ipinfo.io/json >> output.txt
         echo "$(<output.txt )"
